-- 1. 사용자 프로필 테이블 (권한 분리용)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  name text,
  email text,
  is_expert boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 사용자 프로필에 대한 RLS(Row Level Security) 설정
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone."
  ON profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile."
  ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile."
  ON profiles FOR UPDATE USING (auth.uid() = id);


-- 2. 서비스 요청서(의뢰) 테이블
CREATE TABLE public.service_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  budget numeric,
  deadline date,
  categories text[],
  orderer_email text,
  status text DEFAULT 'pending',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid REFERENCES auth.users
);

-- 서비스 요청서 RLS 설정
ALTER TABLE public.service_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service requests are viewable by everyone."
  ON service_requests FOR SELECT USING (true);

CREATE POLICY "Anyone can insert requests"
  ON service_requests FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update own requests"
  ON service_requests FOR UPDATE USING (auth.uid() = user_id);

-- 3. 전문가 상세 프로필 테이블
-- storage.ts의 getStoredProfile / saveProfile 함수가 참조하는 테이블
-- 배열 필드는 jsonb로 저장 (Supabase JS 클라이언트가 자동으로 JS 배열로 변환)
CREATE TABLE IF NOT EXISTS public.expert_profiles (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    image_url text,
    profession text,
    name text,
    one_liner text,
    greeting text,
    activities jsonb DEFAULT '[]'::jsonb,
    awards jsonb DEFAULT '[]'::jsonb,
    ai_tools jsonb DEFAULT '[]'::jsonb,
    edit_tools jsonb DEFAULT '[]'::jsonb,
    packages jsonb DEFAULT '{}'::jsonb,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 전문가 프로필 RLS 설정
ALTER TABLE public.expert_profiles ENABLE ROW LEVEL SECURITY;

-- 모든 사용자가 전문가 프로필을 조회 가능 (공개 프로필)
CREATE POLICY "Users can view expert profiles"
    ON public.expert_profiles FOR SELECT
    USING (true);

-- 본인 프로필만 생성 가능
CREATE POLICY "Users can insert own profile"
    ON public.expert_profiles FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- 본인 프로필만 수정 가능
CREATE POLICY "Users can update own profile"
    ON public.expert_profiles FOR UPDATE
    USING (auth.uid() = user_id);

