import type { AdminSnapshot } from '../lib/adminStorage';

export const adminSnapshot: AdminSnapshot = {
    source: 'local',
    profiles: [
        {
            id: 'user-admin-01',
            email: 'benet9827@gmail.com',
            name: '관리자',
            avatarUrl: '',
            isExpert: true,
            createdAt: '2026-06-01T00:00:00.000Z',
        },
    ],
    products: [
        {
            id: 'product-admin-01',
            expertId: 'expert-admin-01',
            expertName: '한석준',
            title: 'AI 영상 제작',
            category: 'ai-video-shortform',
            summary: '숏폼 제작',
            description: 'AI 숏폼 영상 제작',
            sampleLinks: [],
            sampleImageUrl: 'https://example.com/product.jpg',
            startingPrice: 50000,
            deliveryDays: 3,
            revisionCount: 1,
            status: 'published',
            displayOrder: 1,
            isFeatured: false,
            packages: {
                standard: {
                    name: 'Standard',
                    price: 50000,
                    deliveryDays: 3,
                    revisionCount: 1,
                    included: ['영상 1개'],
                },
                deluxe: null,
                premium: null,
            },
        },
        {
            id: 'product-admin-02',
            expertId: 'expert-admin-01',
            expertName: '한석준',
            title: 'AI 이미지 제작',
            category: 'ai-image-character',
            summary: '이미지 시안 제작',
            description: 'AI 이미지 시안 제작',
            sampleLinks: [],
            sampleImageUrl: 'https://example.com/product-2.jpg',
            startingPrice: 30000,
            deliveryDays: 2,
            revisionCount: 1,
            status: 'hidden',
            displayOrder: 2,
            isFeatured: true,
            packages: {
                standard: {
                    name: 'Standard',
                    price: 30000,
                    deliveryDays: 2,
                    revisionCount: 1,
                    included: ['이미지 1개'],
                },
                deluxe: null,
                premium: null,
            },
        },
    ],
    serviceRequests: [
        {
            id: 'request-admin-01',
            title: '숏폼 의뢰',
            description: '광고 숏폼',
            budget: '',
            deadline: '2026-07-05',
            categories: [],
            createdAt: '2026-07-01T00:00:00.000Z',
            clientId: 'client-admin-01',
            expertId: 'expert-admin-01',
            status: 'pending',
            productId: 'product-admin-01',
            selectedPackage: 'standard',
        },
    ],
    proposals: [
        {
            id: 'proposal-admin-01',
            requestId: 'request-admin-01',
            clientId: 'client-admin-01',
            expertId: 'expert-admin-01',
            title: '숏폼 제안서',
            scope: '영상 제작',
            deliverables: ['영상'],
            totalPrice: 50000,
            deliveryDays: 3,
            revisionCount: 1,
            progressType: 'single',
            milestones: [],
            commercialUseAllowed: true,
            sourceFileIncluded: false,
            status: 'accepted',
            paymentStatus: 'paid',
            expiresAt: '2026-07-10T00:00:00.000Z',
        },
    ],
    works: [
        {
            id: 'work-admin-01',
            proposalId: 'proposal-admin-01',
            requestId: 'request-admin-01',
            clientId: 'client-admin-01',
            expertId: 'expert-admin-01',
            title: '숏폼 작업방',
            progressType: 'single',
            status: 'in_progress',
            totalPrice: 50000,
            settlementStatus: 'held',
            stepIds: [],
        },
    ],
    consultations: [
        {
            id: 'consultation-admin-01',
            clientId: 'client-admin-01',
            expertId: 'expert-admin-01',
            productId: 'product-admin-01',
            status: 'open',
            title: '가격 문의',
            lastMessageAt: '2026-07-01T00:00:00.000Z',
            createdAt: '2026-07-01T00:00:00.000Z',
        },
    ],
    consultationMessages: [
        {
            id: 'consultation-message-admin-01',
            consultationId: 'consultation-admin-01',
            senderId: 'client-admin-01',
            body: 'Need price estimate for shortform.',
            attachmentUrls: [],
            createdAt: '2026-07-01T00:10:00.000Z',
        },
    ],
    workMessages: [
        {
            id: 'work-message-admin-01',
            workId: 'work-admin-01',
            senderId: 'expert-admin-01',
            body: 'Draft delivery is ready.',
            attachmentUrls: [],
            createdAt: '2026-07-01T00:20:00.000Z',
        },
        {
            id: 'work-message-admin-02',
            workId: 'work-admin-01',
            senderId: 'client-admin-01',
            body: 'Please contact me at client@example.com outside the platform.',
            attachmentUrls: [],
            createdAt: '2026-07-01T00:25:00.000Z',
        },
    ],
    reviews: [
        {
            id: 'review-admin-01',
            workId: 'work-admin-01',
            clientId: 'client-admin-01',
            expertId: 'expert-admin-01',
            rating: 5,
            content: '좋았습니다.',
            status: 'published',
            createdAt: '2026-07-01T00:00:00.000Z',
        },
    ],
    reports: [
        {
            id: 'report-admin-01',
            reporterId: 'client-admin-01',
            targetType: 'product',
            targetId: 'product-admin-01',
            reason: '외부 연락처 유도 의심',
            status: 'pending',
            severity: 'high',
            createdAt: '2026-07-01T00:40:00.000Z',
        },
    ],
    adminActions: [],
};
